config/routes.rb
Rails.application.routes.draw do
  resources :users
  root to: "students#index"
  resources :students
  resources :institutions
  get "/search"=>"students#search_list"
  get '/register' =>"students#new"
  get '/login' =>"users#login"
  post '/verify_login' =>"users#verify_login"
  get '/update_status' =>"students#update_status"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/institution.rb
class Institution < ApplicationRecord
    has_many :students
    belongs_to :country
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :set_institution, only: [:show, :edit, :update, :destroy]

  # GET /institutions
  # GET /institutions.json
  def index
    @institutions = Institution.all
  end

  # GET /institutions/1
  # GET /institutions/1.json
  def show
  end

  # GET /institutions/new
  def new
    @institution = Institution.new
  end

  # GET /institutions/1/edit
  def edit
  end

  # POST /institutions
  # POST /institutions.json
  def create
    @institution = Institution.new(institution_params)

    respond_to do |format|
      if @institution.save
        format.html { redirect_to @institution, notice: 'Institution was successfully created.' }
        format.json { render :show, status: :created, location: @institution }
      else
        format.html { render :new }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institutions/1
  # PATCH/PUT /institutions/1.json
  def update
    respond_to do |format|
      if @institution.update(institution_params)
        format.html { redirect_to @institution, notice: 'Institution was successfully updated.' }
        format.json { render :show, status: :ok, location: @institution }
      else
        format.html { render :edit }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.json
  def destroy
    @institution.destroy
    respond_to do |format|
      format.html { redirect_to institutions_url, notice: 'Institution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institution
      @institution = Institution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institution_params
      params.require(:institution).permit(:name, :address, :phone,:country_id)
    end
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/institutions/_form.html.erb
<%= form_with(model: institution, local: true) do |form| %>
  <% if institution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(institution.errors.count, "error") %> prohibited this institution from being saved:</h2>

      <ul>
      <% institution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <label for="name" class="control-label col-sm-3"> Name:</label>
    <div class="col-sm-8">
      <%= form.text_field :name %>
    </div>
  </div>

  <div class="form-group row">
    <label for="name" class="control-label col-sm-3"> Address:</label>
    <div class="col-sm-8">
      <%= form.text_area :address %>
    </div>
  </div>

  <div class="form-group row">
    <label for="name" class="control-label col-sm-3"> Phone:</label>
    <div class="col-sm-8">
      <%= form.text_field :phone %>
    </div>
  </div>
  <div class="form-group row">
    <label for="country" class="control-label col-sm-3">Country:</label>
    <div class="col-sm-8">
        <%#= collection_select("institution", "country", { include_blank: 'Select a country' })%>
        <%= collection_select(:institution, :country_id, Country.all, :id, :country_name,
                 {:prompt => 'Please select the country'})%>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/institutions/edit.html.erb
<h1>Editing Institution</h1>

<%= render 'form', institution: @institution %>

<%= link_to 'Show', @institution %> |
<%= link_to 'Back', institutions_path %>

app/views/institutions/index.html.erb
<p id="notice"><%= notice %></p>

 <div class="card card-cascade narrower">
          <div class="view view-cascade gradient-card-header blue-gradient narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">

            <a href="" class="white-text mx-3">Institutions</a>
             <div>
              <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2 waves-effect waves-light"><a href='institutions/new'><i class="fas fa-pencil-alt mt-0" style='color:white'>New</i></a></button>
             
            </div>
          
          </div>
           
          

          <div class="px-4">

            <div class="table-wrapper">
              
              <table class="table table-hover mb-0">

               
                <thead>
                  <tr>
                    <th class="th-lg">
                       Name
                    </th>
                    <th class="th-lg">
                      Address
                    </th>
                    <th class="th-lg">
                      Phone
                    </th>
                    <th class="th-lg">
                      Country
                    </th>
          

                  </tr>
                </thead>
                <tbody>
                   <% @institutions.each do |institution| %>
                  <tr>
                   
                    <td><%= institution.name %></td>
                    <td><%= institution.address%></td>
                    <td><%= institution.phone%></td>
                    <td><%= institution.country.country_name rescue nil%></td>
                    <td><%= link_to 'Show', institution %></td>
        <td><%= link_to 'Edit', edit_institution_path(institution) %></td>
        <td><%= link_to 'Destroy', institution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                  <%end%>
                </tbody>                
              </table>             
            </div>
          </div>
        </div>

<%#= link_to 'New Institution', new_institution_path %>

app/views/institutions/new.html.erb
<h1>New Institution</h1>

<%= render 'form', institution: @institution %>

<%= link_to 'Back', institutions_path %>

app/views/institutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @institution.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @institution.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @institution.phone %>
</p>

<p>
	<strong>Country:</strong>
	<%= @institution.country.country_name%>
</p>
<%= link_to 'Edit', edit_institution_path(@institution) %> |
<%= link_to 'Back', institutions_path %>